foreground              #e6edf3
background              #0d1117
selection_foreground    #e6edf3
selection_background    #264f78

cursor                  #58a6ff
cursor_text_color       #0d1117

url_color               #58a6ff

color0  #6e7681
color8  #8b949e

color1  #ff7b72
color9  #ffa198

color2  #3fb950
color10 #56d364

color3  #d29922
color11 #e3b341

color4  #58a6ff
color12 #79c0ff

color5  #bc8cff
color13 #d2a8ff

color6  #39c5cf
color14 #56d4dd

color7  #b1bac4
color15 #f0f6fc

active_tab_foreground   #0d1117
active_tab_background   #58a6ff
inactive_tab_foreground #8b949e
inactive_tab_background #161b22
